### ISSUE TITLE
GWAT estimates

### ISSUE THREAD

**Issue by Saman-M-B** [fabern/LWFBrook90.jl#86]
Hi, I was wondering if there is a function to retrieve the values of storage but in different depths such as GWAT or since the model considers these as storage, you can only get the final (deepest layer) values? Cause I think the LWFBrook90R model provides these values per soil layer for each timestep.

**Comment by fabern** [comment]
Hi Saman,

Sorry for the late reply. Your message has somehow escaped from my view.

Yes, since version 0.9.9 there is a way. This version introduced the functions `get_states`,  `get_fluxes` (and `get_forcing`). So for your request use `get_states` to get GWAT or SWAT from certain depths. This gives you tables with the storage or fluxes at each time step. Have a look at the documentation here: https://fabern.github.io/LWFBrook90.jl/stable/generated/example-script-01/#Postprocessing:-Extract-values

Hope this helps.

Best regards, Fabian
